<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Report</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; }
        h1 { font-size: 18px; margin-bottom: 10px; }
        .meta { margin-bottom: 10px; }
        .grid { display: flex; gap: 10px; margin-bottom: 10px; }
        .card { border: 1px solid #ccc; padding: 8px; flex: 1; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 6px; }
        th { background: #f3f3f3; }
    </style>
</head>
<body>
    <h1>{{ $school_name }} - Attendance Report</h1>
    <div class="meta">
        <div>Type: {{ ucfirst(str_replace('_', ' ', $type)) }}</div>
        <div>Date Range: {{ $date_from }} to {{ $date_to }}</div>
        <div>Generated By: {{ $generated_by }}</div>
        <div>Generated At: {{ now()->format('Y-m-d H:i:s') }}</div>
    </div>
    <div class="grid">
        <div class="card">
            <div><strong>Teacher Daily</strong></div>
            <div>Present: {{ $summary['teacher']['present'] }}</div>
            <div>Absent: {{ $summary['teacher']['absent'] }}</div>
            <div>Late: {{ $summary['teacher']['late'] }}</div>
            <div>Excused: {{ $summary['teacher']['excused'] }}</div>
        </div>
        <div class="card">
            <div><strong>Student Daily</strong></div>
            <div>Present: {{ $summary['student_daily']['present'] }}</div>
            <div>Absent: {{ $summary['student_daily']['absent'] }}</div>
            <div>Late: {{ $summary['student_daily']['late'] }}</div>
            <div>Excused: {{ $summary['student_daily']['excused'] }}</div>
        </div>
        <div class="card">
            <div><strong>Student Session</strong></div>
            <div>Present: {{ $summary['student_session']['present'] }}</div>
            <div>Absent: {{ $summary['student_session']['absent'] }}</div>
            <div>Late: {{ $summary['student_session']['late'] }}</div>
            <div>Excused: {{ $summary['student_session']['excused'] }}</div>
        </div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                @if ($type !== 'teacher')
                    <th>Section</th>
                @endif
                @if ($type === 'student_session')
                    <th>Subject</th>
                @endif
                <th>{{ $type === 'teacher' ? 'Teacher' : 'Student' }}</th>
                @if ($type !== 'teacher')
                    <th>Admission</th>
                @endif
                @if ($type === 'student_session')
                    <th>Period</th>
                @endif
                <th>Status</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($records as $row)
                <tr>
                    <td>{{ $row->date }}</td>
                    @if ($type !== 'teacher')
                        <td>
                            {{ optional($row->classSection->grade)->grade_name }} - {{ optional($row->classSection)->section_name }}
                        </td>
                    @endif
                    @if ($type === 'student_session')
                        <td>{{ optional($row->subject)->subject_name }}</td>
                    @endif
                    <td>
                        @if ($type === 'teacher')
                            {{ optional($row->teacher->user)->name ?? optional($row->teacher->user)->first_name . ' ' . optional($row->teacher->user)->last_name }}
                        @else
                            {{ optional($row->student->user)->name ?? optional($row->student->user)->first_name . ' ' . optional($row->student->user)->last_name }}
                        @endif
                    </td>
                    @if ($type !== 'teacher')
                        <td>{{ optional($row->student)->admission_number }}</td>
                    @endif
                    @if ($type === 'student_session')
                        <td>{{ $row->period }}</td>
                    @endif
                    <td>{{ $row->status }}</td>
                    <td>{{ $row->remarks }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>

