<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 10pt; }
        .header { width: 100%; border-bottom: 2px solid #333; margin-bottom: 20px; padding-bottom: 10px; }
        .logo { font-size: 24px; font-weight: bold; }
        .meta { text-align: right; font-size: 9pt; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; }
        .text-right { text-align: right; }
        .filters { margin-bottom: 15px; font-size: 9pt; background: #f9f9f9; padding: 10px; border: 1px solid #eee; }
        .footer { position: fixed; bottom: 0; width: 100%; font-size: 8pt; text-align: center; color: #777; border-top: 1px solid #ddd; padding-top: 5px; }
        .page-number:after { content: counter(page); }
    </style>
</head>
<body>
    <div class="header">
        <div style="float:left">
            <div class="logo">{{ setting('app_name') }}</div>
            <div>{{ $title }}</div>
        </div>
        <div style="float:right; text-align:right">
            <div>Date: {{ $date }}</div>
            <div>Generated by: {{ $generated_by }}</div>
        </div>
        <div style="clear:both"></div>
    </div>

    {{-- <div class="filters">
        <strong>Applied Filters:</strong><br>
        @foreach($filters as $key => $value)
            @if($value && $value !== 'all')
                <span style="margin-right: 15px">
                    <strong>{{ ucwords(str_replace('_', ' ', $key)) }}:</strong> {{ $value }}
                </span>
            @endif
        @endforeach
    </div> --}}

    <table>
        <thead>
            <tr>
                <th>Receipt #</th>
                <th>Student</th>
                <th>Adm No</th>
                <th>Year</th>
                <th>Method</th>
                <th>Reference</th>
                <th>Date</th>
                <th>Staff</th>
                <th class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payments as $payment)
            <tr>
                <td>{{ $payment->receipt->receipt_number ?? '-' }}</td>
                <td>{{ $payment->student->user->first_name ?? '' }} {{ $payment->student->user->last_name ?? '' }}</td>
                <td>{{ $payment->student->admission_number ?? '-' }}</td>
                <td>{{ $payment->bill->academicYear->year_name ?? '-' }}</td>
                <td>{{ $payment->payment_method }}</td>
                <td>{{ $payment->transaction_reference }}</td>
                <td>{{ $payment->payment_date }}</td>
                <td>{{ $payment->receivedBy->name ?? 'System' }}</td>
                <td class="text-right">{{ number_format($payment->amount_paid, 2) }}</td>
            </tr>
            @endforeach
            <tr style="font-weight: bold; background-color: #f0f0f0;">
                <td colspan="9" class="text-right">Total Collected:</td>
                <td class="text-right">{{ number_format($total_amount, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Page <span class="page-number"></span>
    </div>
</body>
</html>
